### ISSUE TITLE
New setups from nodecg-cli cannot read properties of undefined for src/server functions

### ISSUE THREAD

**Issue by starrodkirby86** [nodecg/nodecg#746] opened 2024-08-29 08:16 UTC
# Steps to Reproduce
```
# Must be >=2.0. v1.9 works OK.
nodecg setup
```

```
Finding latest release that satisfies semver range 2.2.2... done!
Downloading v2.2.2 from npm... done!
Installing production npm dependencies... done!
NodeCG (v2.2.2) installed to /my_nodecg_installation_directory
```

When attempting to start nodecg with at least one bundle, the following will occur instead of nodecg successfully mounting the bundle:
```
2024-08-29 00:11:49 - info: [server] Starting NodeCG 2.2.2 (Running on Node.js v20.9.0)
TypeError: Cannot read properties of undefined (reading 'load')
    at <anonymous> (/my_nodecg_installation_directory/src/server/bundle-parser/panels.ts:54:21)
    at Array.forEach (<anonymous>)
    at default_1 (/my_nodecg_installation_directory/src/server/bundle-parser/panels.ts:36:18)
    at default_1 (/my_nodecg_installation_directory/src/server/bundle-parser/index.ts:48:23)
    at <anonymous> (/my_nodecg_installation_directory/src/server/bundle-manager.ts:185:31)
    at Array.forEach (<anonymous>)
    at <anonymous> (/my_nodecg_installation_directory/src/server/bundle-manager.ts:161:18)
    at Array.forEach (<anonymous>)
    at BundleManager (/my_nodecg_installation_directory/src/server/bundle-manager.ts:100:16)
    at NodeCGServer.<anonymous> (/my_nodecg_installation_directory/src/server/server/index.ts:205:25)
node:child_process:965
    throw err;
    ^
```

Fortunately, of course, cloning from `nodecg.git` and building from there works fine.

## Environment
Versions Tested:
8.6.8

Operating System:
Ubuntu 20.04.1 LTS on WSL2 5.15.153.1-microsoft-standard-WSL2

Node versions tested:
- v18.16.0
- v20.9.0
- v20.11.1

## Other Notes
I've had previous instances of nodecg that were setup back in March 2024[v2.2.1](https://github.com/nodecg/nodecg/releases/tag/v2.2.1). These still operate fine with existing bundles. It's now only instances of new nodecg apps set up via nodecg-cli at this point. I'm not exactly sure whether something under the hood has changed (eg. a package inside node_modules updating and regressing), but at this current state setting up via nodecg-cli seems non-functional.

**Comment by tobybaratta** [comment] 2024-09-04 00:35
As per discussed in the Discord, rolling out a 2.2.3 as `latest` that works properly with `nodecg-cli` -- assigned to Hoishin :)

**Comment by noahm** [comment] 2024-09-08 19:19
I finally tracked this issue down. It's a result of `cheerio` 1.0.0 being released a month ago. It has some breaking changes and the project is currently using an old RC version. When you install nodecg with the CLI it doesn't have the npm lockfile included, so you get the newest release of cheerio and stuff is broken as a result. You can work around the issue for the moment by running `npm install cheerio@1.0.0-rc.12` inside any broken install created with the CLI, and I'll open a PR to upgrade the project to the final version of cheerio which will solve this one issue entirely.

In the future you should consider shipping the lockfile in the published versions of nodecg to avoid new dep versions from breaking nodecg like this again.

**Comment by noahm** [comment] 2024-09-08 19:37
@tobybaratta @Hoishin PR is up. Also note that the previously proposed fix of rolling `2.2.1` out again as `2.2.3` won't fix anything because the issue isn't a result of changes made in nodecg. You need my PR and a new release to fix it (and/or to start shipping the lockfile with the releases)

**Comment by tobybaratta** [comment] 2024-09-08 21:58
Thanks Noah! 

I'm not sure on whether we would want to publish the package-lock with NodeCG -- my first thought was immediate "yes, of course, so people get what is guaranteed working with it's sub-dependencies". However, reading more on the `npm` side and about `shrinkwrap` behavior, I am a little less convinced that it would do more overall good than harm.

I think instead we might want to do more what your PR does here - be less accepting of any minor changes on dependencies while still taking bug fix PRs from larger dependencies (that can be trusted to not actually break us). I don't feel particularly strongly about it, but do want to make sure we avoid this again while still following best practices for maintainers. We can open another discussion thread on that or pull it to the discord. 

I set the tests running on your PR, for now!

**Comment by noahm** [comment] 2024-09-09 00:55
it looks like the windows tests all fail and the Mac tests hang forever. is that expected?

**Comment by noahm** [comment] 2024-09-09 00:58
> I am a little less convinced that it would do more overall good than harm.

What harm do you see in including it? Do you see users getting newer releases on nodecg's dependencies out of band of your own releases as desirable?

**Closed as completed** 2024-10-10 19:46 UTC
Labels: bug, breaking change
