### ISSUE TITLE
No Error logs for server exceptions

### ISSUE THREAD

**Issue by TreZc0** [nodecg/nodecg#524] opened 2019-09-15 22:30 UTC
Since version 1.5.0, exceptions will not trigger any error log anymore for most errors (TypeErrors, exceptions...)
The server is stopped by a newly added exithook introduced by a change to update the persistence process:
https://github.com/nodecg/nodecg/commit/16fcefd75c57c92fc81ead0aa8fc95b19b6a2ee8#diff-168726dbe96b3ce427e7fedce31bb0bcR73-R75 - line 73 in the index.js.

**Comment by Lange** [comment] 2019-09-15 23:44
One potential fix would be to put the `process.exit` within a `setImmediate`, which should give Node.js enough time to flush stdout and stderr before closing. If that isn't enough, then we'd probably need to throw it in like a `setTimeout` with a 100ms delay or something. I don't know if there's a programmatic way to actually know for sure if node has flushed stdout and stderr. This is a common problem with Node.

**Comment by Lange** [comment] 2019-09-15 23:45
Actually... there is no `process.exit` being called here. So the issue is likely something else?

**Comment by TreZc0** [comment] 2019-09-16 05:35
I am not entirely sure why either, but commenting out the server.stop() fixes the issue.
I imagine server.stop() automatically triggers a process.exit somewhere?

Actually, I quickly browsed through the docs, apparently, Not sure if I understand it correctly, but server.stop() seems unintended, as in that's not a valid state for the app?

If I am right, the server process that would handle the error or at least output it gets stopped before it outputs the error, and that ends or, i fear, crashes the app as it can't handle running without a server?

**Comment by Lange** [comment] 2019-09-18 15:01
@TreZc0 I'm having a hard time reproducing this locally, do you have a minimal repro you can share?

**Comment by TreZc0** [comment] 2019-09-18 23:17
Will try to get a small error case up tmrw.

**Comment by Lange** [comment] 2020-03-08 22:14
@TreZc0 Any luck with a reproduction case?

**Comment by TreZc0** [comment] 2020-03-09 00:13
I remember us having a talk about it on discord and then finding a solution for our case....

However, since you could never replicate it, we are still to this day unsure what's the reason behind it in our special environment.
Uncaught Exceptions did not log to console.
We did however fix it for us by adding a simple exitcode check in the index.js for the "stopped" event:
`	.on('stopped', () => {
		if (!process.exitCode)
			process.exit(0)
	});
`

**Comment by dragonbane0** [comment] 2020-03-09 00:17
This situation seemed to arise by your 

```
if (global.exitOnUncaught) {
  process.exit(1);
}
```

code firing and then the server "stopped" event firing afterwards with exit code 0. Firing 2 process.exits with different exit IDs back to back seems like a maybe-not-optimal practice to me at best and at worst it might cause issues like in our case. We fixed it by not firing that second server process.exit(0) if there is already an exit code set by a different process.exit()

**Comment by Lange** [comment] 2020-03-09 00:26
Oh that makes sense, yeah a PR with y'alls fix sounds reasonable.

**Comment by dragonbane0** [comment] 2020-03-09 15:50
Done. https://github.com/nodecg/nodecg/pull/543

**Closed as completed** 2020-03-09 21:27 UTC
